version: '3.9'

services:
  nginx:
    image: nginx
    restart: always
    container_name: nginx
    volumes:
    - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
    - ./openapi.yaml:/etc/nginx/openapi/openapi.yaml:ro
    ports:
      - 8080:80

  account-service:
    container_name: account-service
    restart: always
    build:
      context: ./account_service
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://accounts-db:5432/accounts
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=aboba
      - REDIS_HOST=accounts-redis
      - REDIS_PORT=6379
    depends_on:
      - accounts-redis
      - kafka
      - accounts-db

  redirect-service:
    container_name: redirect-service
    restart: always
    build:
      context: ./redirect_service
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redirect-service-redis
      - REDIS_PORT=6379
    depends_on:
      - codes-handler
      - kafka
      - redirect-service-redis

  qr-code-generator-service:
    container_name: qr-code-generator-service
    restart: always
    build:
      context: ./qr_code_generator
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=qr-code-generator-redis
      - REDIS_PORT=6379
      - QR_CODE_HOST=http://192.168.1.206:8080/
    depends_on:
      - kafka
      - qr-code-generator-redis

  auth-service:
    container_name: auth-service
    restart: always
    build:
      context: ./auth_service
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=auth-redis
      - REDIS_PORT=6379
    depends_on:
      - account-service
      - kafka
      - auth-redis

  codes-handler:
    container_name: codes-handler
    restart: always
    build:
      context: ./codes_handler/
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://codes-handler-db:5432/codes
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=aboba
      - REDIS_HOST=codes-handler-redis
      - REDIS_PORT=6379
    depends_on:
      - kafka
      - codes-handler-db
      - codes-handler-redis

  codes-handler-db:
    image: postgres
    container_name: codes-handler-db
    restart: always
    environment:
      POSTGRES_PASSWORD: aboba
      POSTGRES_USER: postgres
      POSTGRES_DB: codes
    volumes:
      - codes-handler-db:/var/lib/postgresql/data

  qr-code-generator-redis:
    image: redis
    restart: always
    container_name: qr-code-generator-redis
    command: redis-server
    volumes:
      - qr-code-generator-redis:/data

  codes-handler-redis:
    image: redis
    restart: always
    container_name: codes-handler-redis
    command: redis-server
    volumes:
      - codes-handler-redis:/data

  redirect-service-redis:
    image: redis
    restart: always
    container_name: redirect-service-redis
    command: redis-server
    volumes:
      - redirect-service-redis:/data

  auth-redis:
    image: redis
    restart: always
    container_name: auth-redis
    command: redis-server
    volumes:
      - auth-redis:/data

  accounts-redis:
    image: redis
    restart: always
    container_name: accounts-redis
    command: redis-server
    volumes:
      - accounts-redis:/data

  accounts-db:
    image: postgres
    container_name: accounts-db
    restart: always
    environment:
      POSTGRES_PASSWORD: aboba
      POSTGRES_USER: postgres
      POSTGRES_DB: accounts
    volumes:
      - accounts-db:/var/lib/postgresql/data

  kafka:
    image: apache/kafka
    restart: always
    container_name: kafka
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3

volumes:
  codes-handler-db:
    driver: local
  codes-handler-redis:
    driver: local
  redirect-service-redis:
    driver: local
  auth-redis:
    driver: local
  accounts-redis:
    driver: local
  qr-code-generator-redis:
    driver: local
  accounts-db:
    driver: local
